@startuml
actor User
User -> Controller : click "Next slide"
Controller -> SlideIterator : hasNext()
Controller -> SlideIterator : next()
SlideIterator -> SlideCollection : getSlide()
SlideCollection --> SlideIterator : Slide
SlideIterator --> Controller : Slide
Controller -> Slide : getImageView()
@enduml
